---
# yamllint disable rule:line-length
name: "Sign Gluon Manifest"
description: "Sign Gluon Manifest using the build-gluon container"
inputs:
  gluon-path:
    description: 'Path to an initialized Gluon repository'
    required: true
  container-version:
    description: 'Container version to use'
    default: 'master'
  manifest:
    description: 'Location of the manifest file to sign'
    required: true
  signing-key:
    description: 'ECDSA key to sign manifest with'
    required: true
  write-signature:
    description: 'Write signature to manifest file'
    default: true

outputs:
  signature:
    description: 'Signature output'
    value: ${{ steps.signature-output.outputs.signature }}

runs:
  using: 'composite'
  steps:
    - run: docker build --build-arg CONTAINER --build-arg VERSION -t sdk $GITHUB_ACTION_PATH
      env:
        VERSION: ${{ inputs.container-version }}
      shell: bash
    - run: mkdir -p ${RUNNER_TEMP}/workdir
      shell: bash
    - run: echo "${{ inputs.signing-key }}" > "${RUNNER_TEMP}/workdir/signing.key"
      shell: bash
    - run: cp "${{ inputs.manifest }}" "${RUNNER_TEMP}/workdir/signing.manifest"
      shell: bash
    - run: |
        docker run --rm \
          --user "$(id -u):$(id -g)" \
          --volume "${GITHUB_WORKSPACE}/${ACTION_GLUON_PATH}:/gluon/gluon-repo" \
          --volume "${RUNNER_TEMP}/workdir:/gluon/workdir" \
          sdk
      env:
        ACTION_GLUON_PATH: ${{ inputs.gluon-path }}
      shell: bash
    - run: cp "${RUNNER_TEMP}/workdir/signing.manifest" "${{ inputs.manifest }}"
      shell: bash
      if: inputs.write-signature == 'true'
    - run: echo "signature=$(tail -n1 "${RUNNER_TEMP}/workdir/signing.manifest")" > $GITHUB_OUTPUT
      id: signature-output
      shell: bash
